[build]
  base = "/"
  publish = "public/"
  command = "yarn build"
  environment = { YARN_VERSION = "1.22.10" }

[[plugins]]
  package = "./netlify/plugins/netlify-plugin-env-config"

[[redirects]]
  from = "/is"
  to = "/images/code4rena_is.pdf"
  status = 200  

[context.production.environment]
  C4_ENV = "production"

[context.deploy-preview]
  ignore = "bash ./netlify-ignore-branch.sh"

[context.deploy-preview.environment]
  C4_ENV = "staging"

[context.staging.environment]
  C4_ENV = "staging"

[functions]
  directory = "functions/"
  included_files = ["_data/contests/*"]
